/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sangram;

public class App {
    public static void main(String[] args) {
        (new ArrayListTest()).test();
    }
}
